log:
  level: info
  file: ""
  production: false


plugins:

  - tag: cache
    type: cache
    args:
      size: 1024
      lazy_cache_ttl: 0

  - tag: hosts
    type: hosts
    args:
      files:
        - "./hosts"

  - tag: upstreams
    type: forward
    args:
      upstreams:
        - tag: cloudflare_doh
          addr: https://dns.cloudflare.com/dns-query
          enable_pipeline: true
          idle_timeout: 50
          insecure_skip_verify: true

        - tag: opendns_doh
          addr: https://146.112.41.2/dns-query
          enable_pipeline: true
          idle_timeout: 50
          insecure_skip_verify: true

        - tag: twinc_tls
          addr: tls://101.101.101.101
          enable_pipeline: true
          idle_timeout: 50
          insecure_skip_verify: true

        - tag: dnspod
          addr: tls://1.12.12.12
          enable_pipeline: true
          idle_timeout: 30
          insecure_skip_verify: true

        - tag: aliyun
          addr: tls://223.5.5.5
          bootstrap: 223.5.5.5
          enable_pipeline: true
          idle_timeout: 30
          insecure_skip_verify: true

  # 本地域名的规则
  - tag: local_seq
    type: sequence
    args:
      - exec: $upstreams dnspod aliyun

  - tag: remote_seq
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $upstreams twinc_tls opendns_doh cloudflare_doh

  - tag: local_must_has_cn
    type: sequence
    args:
      - exec: $upstreams dnspod aliyun
      - matches: "!resp_ip &./geoip_cn.txt"
        exec: drop_resp

  - tag: fallback_ip
    type: fallback
    args:
      primary: local_must_has_cn
      secondary: remote_seq
      always_standby: true

  - tag: main
    type: sequence
    args:
      - exec: $hosts
      - exec: query_summary entry
      - matches:
          - qname &./geosite_category-ads-all.txt
        exec: reject 0
      - exec: $cache
      - {matches: has_resp, exec: accept}
      - matches:
          - qname &./geosite_cn.txt
        exec: goto local_seq
      - matches:
          - qname &./geosite_geolocation-!cn.txt
        exec: goto remote_seq

      - exec: $fallback_ip

  - tag: server
    type: udp_server
    args:
      entry: main
      listen: 0.0.0.0:53
  - tag: server_tcp
    type: tcp_server
    args:
      entry: main
      listen: 0.0.0.0:53